/*
ston-server

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.13.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PoolStats type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PoolStats{}

// PoolStats struct for PoolStats
type PoolStats struct {
	// Annual percentage yield
	Apy NullableString `json:"apy,omitempty"`
	// Base asset id
	BaseId string `json:"base_id"`
	// Amount of liquidity of base asset
	BaseLiquidity string `json:"base_liquidity"`
	// Base asset name
	BaseName string `json:"base_name"`
	// Base asset symbol
	BaseSymbol string `json:"base_symbol"`
	// volume of base asset
	BaseVolume string `json:"base_volume"`
	// Last asset quota price in base assets
	LastPrice string `json:"last_price"`
	// [DEPRECATED] Liquidity pool token price
	LpPrice string `json:"lp_price"`
	// Liquidity pool token price
	LpPriceUsd string `json:"lp_price_usd"`
	// Address of the pool
	PoolAddress string `json:"pool_address"`
	// Quote asset id
	QuoteId string `json:"quote_id"`
	// Amount of liquidity of quote asset
	QuoteLiquidity string `json:"quote_liquidity"`
	// Quote asset name
	QuoteName string `json:"quote_name"`
	// Quote asset symbol
	QuoteSymbol string `json:"quote_symbol"`
	// Volume of quote asset
	QuoteVolume string `json:"quote_volume"`
	// Address of router
	RouterAddress string `json:"router_address"`
	// URL of the pool
	Url string `json:"url"`
}

type _PoolStats PoolStats

// NewPoolStats instantiates a new PoolStats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPoolStats(baseId string, baseLiquidity string, baseName string, baseSymbol string, baseVolume string, lastPrice string, lpPrice string, lpPriceUsd string, poolAddress string, quoteId string, quoteLiquidity string, quoteName string, quoteSymbol string, quoteVolume string, routerAddress string, url string) *PoolStats {
	this := PoolStats{}
	this.BaseId = baseId
	this.BaseLiquidity = baseLiquidity
	this.BaseName = baseName
	this.BaseSymbol = baseSymbol
	this.BaseVolume = baseVolume
	this.LastPrice = lastPrice
	this.LpPrice = lpPrice
	this.LpPriceUsd = lpPriceUsd
	this.PoolAddress = poolAddress
	this.QuoteId = quoteId
	this.QuoteLiquidity = quoteLiquidity
	this.QuoteName = quoteName
	this.QuoteSymbol = quoteSymbol
	this.QuoteVolume = quoteVolume
	this.RouterAddress = routerAddress
	this.Url = url
	return &this
}

// NewPoolStatsWithDefaults instantiates a new PoolStats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPoolStatsWithDefaults() *PoolStats {
	this := PoolStats{}
	return &this
}

// GetApy returns the Apy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PoolStats) GetApy() string {
	if o == nil || IsNil(o.Apy.Get()) {
		var ret string
		return ret
	}
	return *o.Apy.Get()
}

// GetApyOk returns a tuple with the Apy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PoolStats) GetApyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Apy.Get(), o.Apy.IsSet()
}

// HasApy returns a boolean if a field has been set.
func (o *PoolStats) HasApy() bool {
	if o != nil && o.Apy.IsSet() {
		return true
	}

	return false
}

// SetApy gets a reference to the given NullableString and assigns it to the Apy field.
func (o *PoolStats) SetApy(v string) {
	o.Apy.Set(&v)
}
// SetApyNil sets the value for Apy to be an explicit nil
func (o *PoolStats) SetApyNil() {
	o.Apy.Set(nil)
}

// UnsetApy ensures that no value is present for Apy, not even an explicit nil
func (o *PoolStats) UnsetApy() {
	o.Apy.Unset()
}

// GetBaseId returns the BaseId field value
func (o *PoolStats) GetBaseId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BaseId
}

// GetBaseIdOk returns a tuple with the BaseId field value
// and a boolean to check if the value has been set.
func (o *PoolStats) GetBaseIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BaseId, true
}

// SetBaseId sets field value
func (o *PoolStats) SetBaseId(v string) {
	o.BaseId = v
}

// GetBaseLiquidity returns the BaseLiquidity field value
func (o *PoolStats) GetBaseLiquidity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BaseLiquidity
}

// GetBaseLiquidityOk returns a tuple with the BaseLiquidity field value
// and a boolean to check if the value has been set.
func (o *PoolStats) GetBaseLiquidityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BaseLiquidity, true
}

// SetBaseLiquidity sets field value
func (o *PoolStats) SetBaseLiquidity(v string) {
	o.BaseLiquidity = v
}

// GetBaseName returns the BaseName field value
func (o *PoolStats) GetBaseName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BaseName
}

// GetBaseNameOk returns a tuple with the BaseName field value
// and a boolean to check if the value has been set.
func (o *PoolStats) GetBaseNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BaseName, true
}

// SetBaseName sets field value
func (o *PoolStats) SetBaseName(v string) {
	o.BaseName = v
}

// GetBaseSymbol returns the BaseSymbol field value
func (o *PoolStats) GetBaseSymbol() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BaseSymbol
}

// GetBaseSymbolOk returns a tuple with the BaseSymbol field value
// and a boolean to check if the value has been set.
func (o *PoolStats) GetBaseSymbolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BaseSymbol, true
}

// SetBaseSymbol sets field value
func (o *PoolStats) SetBaseSymbol(v string) {
	o.BaseSymbol = v
}

// GetBaseVolume returns the BaseVolume field value
func (o *PoolStats) GetBaseVolume() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BaseVolume
}

// GetBaseVolumeOk returns a tuple with the BaseVolume field value
// and a boolean to check if the value has been set.
func (o *PoolStats) GetBaseVolumeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BaseVolume, true
}

// SetBaseVolume sets field value
func (o *PoolStats) SetBaseVolume(v string) {
	o.BaseVolume = v
}

// GetLastPrice returns the LastPrice field value
func (o *PoolStats) GetLastPrice() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastPrice
}

// GetLastPriceOk returns a tuple with the LastPrice field value
// and a boolean to check if the value has been set.
func (o *PoolStats) GetLastPriceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastPrice, true
}

// SetLastPrice sets field value
func (o *PoolStats) SetLastPrice(v string) {
	o.LastPrice = v
}

// GetLpPrice returns the LpPrice field value
func (o *PoolStats) GetLpPrice() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LpPrice
}

// GetLpPriceOk returns a tuple with the LpPrice field value
// and a boolean to check if the value has been set.
func (o *PoolStats) GetLpPriceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LpPrice, true
}

// SetLpPrice sets field value
func (o *PoolStats) SetLpPrice(v string) {
	o.LpPrice = v
}

// GetLpPriceUsd returns the LpPriceUsd field value
func (o *PoolStats) GetLpPriceUsd() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LpPriceUsd
}

// GetLpPriceUsdOk returns a tuple with the LpPriceUsd field value
// and a boolean to check if the value has been set.
func (o *PoolStats) GetLpPriceUsdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LpPriceUsd, true
}

// SetLpPriceUsd sets field value
func (o *PoolStats) SetLpPriceUsd(v string) {
	o.LpPriceUsd = v
}

// GetPoolAddress returns the PoolAddress field value
func (o *PoolStats) GetPoolAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PoolAddress
}

// GetPoolAddressOk returns a tuple with the PoolAddress field value
// and a boolean to check if the value has been set.
func (o *PoolStats) GetPoolAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PoolAddress, true
}

// SetPoolAddress sets field value
func (o *PoolStats) SetPoolAddress(v string) {
	o.PoolAddress = v
}

// GetQuoteId returns the QuoteId field value
func (o *PoolStats) GetQuoteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.QuoteId
}

// GetQuoteIdOk returns a tuple with the QuoteId field value
// and a boolean to check if the value has been set.
func (o *PoolStats) GetQuoteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QuoteId, true
}

// SetQuoteId sets field value
func (o *PoolStats) SetQuoteId(v string) {
	o.QuoteId = v
}

// GetQuoteLiquidity returns the QuoteLiquidity field value
func (o *PoolStats) GetQuoteLiquidity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.QuoteLiquidity
}

// GetQuoteLiquidityOk returns a tuple with the QuoteLiquidity field value
// and a boolean to check if the value has been set.
func (o *PoolStats) GetQuoteLiquidityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QuoteLiquidity, true
}

// SetQuoteLiquidity sets field value
func (o *PoolStats) SetQuoteLiquidity(v string) {
	o.QuoteLiquidity = v
}

// GetQuoteName returns the QuoteName field value
func (o *PoolStats) GetQuoteName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.QuoteName
}

// GetQuoteNameOk returns a tuple with the QuoteName field value
// and a boolean to check if the value has been set.
func (o *PoolStats) GetQuoteNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QuoteName, true
}

// SetQuoteName sets field value
func (o *PoolStats) SetQuoteName(v string) {
	o.QuoteName = v
}

// GetQuoteSymbol returns the QuoteSymbol field value
func (o *PoolStats) GetQuoteSymbol() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.QuoteSymbol
}

// GetQuoteSymbolOk returns a tuple with the QuoteSymbol field value
// and a boolean to check if the value has been set.
func (o *PoolStats) GetQuoteSymbolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QuoteSymbol, true
}

// SetQuoteSymbol sets field value
func (o *PoolStats) SetQuoteSymbol(v string) {
	o.QuoteSymbol = v
}

// GetQuoteVolume returns the QuoteVolume field value
func (o *PoolStats) GetQuoteVolume() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.QuoteVolume
}

// GetQuoteVolumeOk returns a tuple with the QuoteVolume field value
// and a boolean to check if the value has been set.
func (o *PoolStats) GetQuoteVolumeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QuoteVolume, true
}

// SetQuoteVolume sets field value
func (o *PoolStats) SetQuoteVolume(v string) {
	o.QuoteVolume = v
}

// GetRouterAddress returns the RouterAddress field value
func (o *PoolStats) GetRouterAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RouterAddress
}

// GetRouterAddressOk returns a tuple with the RouterAddress field value
// and a boolean to check if the value has been set.
func (o *PoolStats) GetRouterAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RouterAddress, true
}

// SetRouterAddress sets field value
func (o *PoolStats) SetRouterAddress(v string) {
	o.RouterAddress = v
}

// GetUrl returns the Url field value
func (o *PoolStats) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *PoolStats) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *PoolStats) SetUrl(v string) {
	o.Url = v
}

func (o PoolStats) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PoolStats) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Apy.IsSet() {
		toSerialize["apy"] = o.Apy.Get()
	}
	toSerialize["base_id"] = o.BaseId
	toSerialize["base_liquidity"] = o.BaseLiquidity
	toSerialize["base_name"] = o.BaseName
	toSerialize["base_symbol"] = o.BaseSymbol
	toSerialize["base_volume"] = o.BaseVolume
	toSerialize["last_price"] = o.LastPrice
	toSerialize["lp_price"] = o.LpPrice
	toSerialize["lp_price_usd"] = o.LpPriceUsd
	toSerialize["pool_address"] = o.PoolAddress
	toSerialize["quote_id"] = o.QuoteId
	toSerialize["quote_liquidity"] = o.QuoteLiquidity
	toSerialize["quote_name"] = o.QuoteName
	toSerialize["quote_symbol"] = o.QuoteSymbol
	toSerialize["quote_volume"] = o.QuoteVolume
	toSerialize["router_address"] = o.RouterAddress
	toSerialize["url"] = o.Url
	return toSerialize, nil
}

func (o *PoolStats) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"base_id",
		"base_liquidity",
		"base_name",
		"base_symbol",
		"base_volume",
		"last_price",
		"lp_price",
		"lp_price_usd",
		"pool_address",
		"quote_id",
		"quote_liquidity",
		"quote_name",
		"quote_symbol",
		"quote_volume",
		"router_address",
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPoolStats := _PoolStats{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPoolStats)

	if err != nil {
		return err
	}

	*o = PoolStats(varPoolStats)

	return err
}

type NullablePoolStats struct {
	value *PoolStats
	isSet bool
}

func (v NullablePoolStats) Get() *PoolStats {
	return v.value
}

func (v *NullablePoolStats) Set(val *PoolStats) {
	v.value = val
	v.isSet = true
}

func (v NullablePoolStats) IsSet() bool {
	return v.isSet
}

func (v *NullablePoolStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePoolStats(val *PoolStats) *NullablePoolStats {
	return &NullablePoolStats{value: val, isSet: true}
}

func (v NullablePoolStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePoolStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


