/*
ston-server

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.13.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetWalletAddress200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetWalletAddress200Response{}

// GetWalletAddress200Response struct for GetWalletAddress200Response
type GetWalletAddress200Response struct {
	Address string `json:"address"`
}

type _GetWalletAddress200Response GetWalletAddress200Response

// NewGetWalletAddress200Response instantiates a new GetWalletAddress200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetWalletAddress200Response(address string) *GetWalletAddress200Response {
	this := GetWalletAddress200Response{}
	this.Address = address
	return &this
}

// NewGetWalletAddress200ResponseWithDefaults instantiates a new GetWalletAddress200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetWalletAddress200ResponseWithDefaults() *GetWalletAddress200Response {
	this := GetWalletAddress200Response{}
	return &this
}

// GetAddress returns the Address field value
func (o *GetWalletAddress200Response) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *GetWalletAddress200Response) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *GetWalletAddress200Response) SetAddress(v string) {
	o.Address = v
}

func (o GetWalletAddress200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetWalletAddress200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["address"] = o.Address
	return toSerialize, nil
}

func (o *GetWalletAddress200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"address",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetWalletAddress200Response := _GetWalletAddress200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetWalletAddress200Response)

	if err != nil {
		return err
	}

	*o = GetWalletAddress200Response(varGetWalletAddress200Response)

	return err
}

type NullableGetWalletAddress200Response struct {
	value *GetWalletAddress200Response
	isSet bool
}

func (v NullableGetWalletAddress200Response) Get() *GetWalletAddress200Response {
	return v.value
}

func (v *NullableGetWalletAddress200Response) Set(val *GetWalletAddress200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetWalletAddress200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetWalletAddress200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetWalletAddress200Response(val *GetWalletAddress200Response) *NullableGetWalletAddress200Response {
	return &NullableGetWalletAddress200Response{value: val, isSet: true}
}

func (v NullableGetWalletAddress200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetWalletAddress200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


