/*
ston-server

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.13.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DexReverseSimulateSwap200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DexReverseSimulateSwap200Response{}

// DexReverseSimulateSwap200Response struct for DexReverseSimulateSwap200Response
type DexReverseSimulateSwap200Response struct {
	// Address of the wallet to which the operation is simulated
	AskAddress string `json:"ask_address"`
	// Token units asked
	AskUnits string `json:"ask_units"`
	// Fee address
	FeeAddress string `json:"fee_address"`
	// fee percent
	FeePercent string `json:"fee_percent"`
	// Fee units
	FeeUnits string `json:"fee_units"`
	// Minimal amount of ask units
	MinAskUnits string `json:"min_ask_units"`
	// Address of the wallet from which the operation is simulated
	OfferAddress string `json:"offer_address"`
	// Token units offered
	OfferUnits string `json:"offer_units"`
	// Address of the pool
	PoolAddress string `json:"pool_address"`
	// Price impact
	PriceImpact string `json:"price_impact"`
	// Address of the operation router
	RouterAddress string `json:"router_address"`
	// Difference between the original price of order and the final price
	SlippageTolerance string `json:"slippage_tolerance"`
	// Swap rate
	SwapRate string `json:"swap_rate"`
}

type _DexReverseSimulateSwap200Response DexReverseSimulateSwap200Response

// NewDexReverseSimulateSwap200Response instantiates a new DexReverseSimulateSwap200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDexReverseSimulateSwap200Response(askAddress string, askUnits string, feeAddress string, feePercent string, feeUnits string, minAskUnits string, offerAddress string, offerUnits string, poolAddress string, priceImpact string, routerAddress string, slippageTolerance string, swapRate string) *DexReverseSimulateSwap200Response {
	this := DexReverseSimulateSwap200Response{}
	this.AskAddress = askAddress
	this.AskUnits = askUnits
	this.FeeAddress = feeAddress
	this.FeePercent = feePercent
	this.FeeUnits = feeUnits
	this.MinAskUnits = minAskUnits
	this.OfferAddress = offerAddress
	this.OfferUnits = offerUnits
	this.PoolAddress = poolAddress
	this.PriceImpact = priceImpact
	this.RouterAddress = routerAddress
	this.SlippageTolerance = slippageTolerance
	this.SwapRate = swapRate
	return &this
}

// NewDexReverseSimulateSwap200ResponseWithDefaults instantiates a new DexReverseSimulateSwap200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDexReverseSimulateSwap200ResponseWithDefaults() *DexReverseSimulateSwap200Response {
	this := DexReverseSimulateSwap200Response{}
	return &this
}

// GetAskAddress returns the AskAddress field value
func (o *DexReverseSimulateSwap200Response) GetAskAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AskAddress
}

// GetAskAddressOk returns a tuple with the AskAddress field value
// and a boolean to check if the value has been set.
func (o *DexReverseSimulateSwap200Response) GetAskAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AskAddress, true
}

// SetAskAddress sets field value
func (o *DexReverseSimulateSwap200Response) SetAskAddress(v string) {
	o.AskAddress = v
}

// GetAskUnits returns the AskUnits field value
func (o *DexReverseSimulateSwap200Response) GetAskUnits() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AskUnits
}

// GetAskUnitsOk returns a tuple with the AskUnits field value
// and a boolean to check if the value has been set.
func (o *DexReverseSimulateSwap200Response) GetAskUnitsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AskUnits, true
}

// SetAskUnits sets field value
func (o *DexReverseSimulateSwap200Response) SetAskUnits(v string) {
	o.AskUnits = v
}

// GetFeeAddress returns the FeeAddress field value
func (o *DexReverseSimulateSwap200Response) GetFeeAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FeeAddress
}

// GetFeeAddressOk returns a tuple with the FeeAddress field value
// and a boolean to check if the value has been set.
func (o *DexReverseSimulateSwap200Response) GetFeeAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FeeAddress, true
}

// SetFeeAddress sets field value
func (o *DexReverseSimulateSwap200Response) SetFeeAddress(v string) {
	o.FeeAddress = v
}

// GetFeePercent returns the FeePercent field value
func (o *DexReverseSimulateSwap200Response) GetFeePercent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FeePercent
}

// GetFeePercentOk returns a tuple with the FeePercent field value
// and a boolean to check if the value has been set.
func (o *DexReverseSimulateSwap200Response) GetFeePercentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FeePercent, true
}

// SetFeePercent sets field value
func (o *DexReverseSimulateSwap200Response) SetFeePercent(v string) {
	o.FeePercent = v
}

// GetFeeUnits returns the FeeUnits field value
func (o *DexReverseSimulateSwap200Response) GetFeeUnits() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FeeUnits
}

// GetFeeUnitsOk returns a tuple with the FeeUnits field value
// and a boolean to check if the value has been set.
func (o *DexReverseSimulateSwap200Response) GetFeeUnitsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FeeUnits, true
}

// SetFeeUnits sets field value
func (o *DexReverseSimulateSwap200Response) SetFeeUnits(v string) {
	o.FeeUnits = v
}

// GetMinAskUnits returns the MinAskUnits field value
func (o *DexReverseSimulateSwap200Response) GetMinAskUnits() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MinAskUnits
}

// GetMinAskUnitsOk returns a tuple with the MinAskUnits field value
// and a boolean to check if the value has been set.
func (o *DexReverseSimulateSwap200Response) GetMinAskUnitsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MinAskUnits, true
}

// SetMinAskUnits sets field value
func (o *DexReverseSimulateSwap200Response) SetMinAskUnits(v string) {
	o.MinAskUnits = v
}

// GetOfferAddress returns the OfferAddress field value
func (o *DexReverseSimulateSwap200Response) GetOfferAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OfferAddress
}

// GetOfferAddressOk returns a tuple with the OfferAddress field value
// and a boolean to check if the value has been set.
func (o *DexReverseSimulateSwap200Response) GetOfferAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OfferAddress, true
}

// SetOfferAddress sets field value
func (o *DexReverseSimulateSwap200Response) SetOfferAddress(v string) {
	o.OfferAddress = v
}

// GetOfferUnits returns the OfferUnits field value
func (o *DexReverseSimulateSwap200Response) GetOfferUnits() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OfferUnits
}

// GetOfferUnitsOk returns a tuple with the OfferUnits field value
// and a boolean to check if the value has been set.
func (o *DexReverseSimulateSwap200Response) GetOfferUnitsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OfferUnits, true
}

// SetOfferUnits sets field value
func (o *DexReverseSimulateSwap200Response) SetOfferUnits(v string) {
	o.OfferUnits = v
}

// GetPoolAddress returns the PoolAddress field value
func (o *DexReverseSimulateSwap200Response) GetPoolAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PoolAddress
}

// GetPoolAddressOk returns a tuple with the PoolAddress field value
// and a boolean to check if the value has been set.
func (o *DexReverseSimulateSwap200Response) GetPoolAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PoolAddress, true
}

// SetPoolAddress sets field value
func (o *DexReverseSimulateSwap200Response) SetPoolAddress(v string) {
	o.PoolAddress = v
}

// GetPriceImpact returns the PriceImpact field value
func (o *DexReverseSimulateSwap200Response) GetPriceImpact() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PriceImpact
}

// GetPriceImpactOk returns a tuple with the PriceImpact field value
// and a boolean to check if the value has been set.
func (o *DexReverseSimulateSwap200Response) GetPriceImpactOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PriceImpact, true
}

// SetPriceImpact sets field value
func (o *DexReverseSimulateSwap200Response) SetPriceImpact(v string) {
	o.PriceImpact = v
}

// GetRouterAddress returns the RouterAddress field value
func (o *DexReverseSimulateSwap200Response) GetRouterAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RouterAddress
}

// GetRouterAddressOk returns a tuple with the RouterAddress field value
// and a boolean to check if the value has been set.
func (o *DexReverseSimulateSwap200Response) GetRouterAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RouterAddress, true
}

// SetRouterAddress sets field value
func (o *DexReverseSimulateSwap200Response) SetRouterAddress(v string) {
	o.RouterAddress = v
}

// GetSlippageTolerance returns the SlippageTolerance field value
func (o *DexReverseSimulateSwap200Response) GetSlippageTolerance() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SlippageTolerance
}

// GetSlippageToleranceOk returns a tuple with the SlippageTolerance field value
// and a boolean to check if the value has been set.
func (o *DexReverseSimulateSwap200Response) GetSlippageToleranceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SlippageTolerance, true
}

// SetSlippageTolerance sets field value
func (o *DexReverseSimulateSwap200Response) SetSlippageTolerance(v string) {
	o.SlippageTolerance = v
}

// GetSwapRate returns the SwapRate field value
func (o *DexReverseSimulateSwap200Response) GetSwapRate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SwapRate
}

// GetSwapRateOk returns a tuple with the SwapRate field value
// and a boolean to check if the value has been set.
func (o *DexReverseSimulateSwap200Response) GetSwapRateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SwapRate, true
}

// SetSwapRate sets field value
func (o *DexReverseSimulateSwap200Response) SetSwapRate(v string) {
	o.SwapRate = v
}

func (o DexReverseSimulateSwap200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DexReverseSimulateSwap200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ask_address"] = o.AskAddress
	toSerialize["ask_units"] = o.AskUnits
	toSerialize["fee_address"] = o.FeeAddress
	toSerialize["fee_percent"] = o.FeePercent
	toSerialize["fee_units"] = o.FeeUnits
	toSerialize["min_ask_units"] = o.MinAskUnits
	toSerialize["offer_address"] = o.OfferAddress
	toSerialize["offer_units"] = o.OfferUnits
	toSerialize["pool_address"] = o.PoolAddress
	toSerialize["price_impact"] = o.PriceImpact
	toSerialize["router_address"] = o.RouterAddress
	toSerialize["slippage_tolerance"] = o.SlippageTolerance
	toSerialize["swap_rate"] = o.SwapRate
	return toSerialize, nil
}

func (o *DexReverseSimulateSwap200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ask_address",
		"ask_units",
		"fee_address",
		"fee_percent",
		"fee_units",
		"min_ask_units",
		"offer_address",
		"offer_units",
		"pool_address",
		"price_impact",
		"router_address",
		"slippage_tolerance",
		"swap_rate",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDexReverseSimulateSwap200Response := _DexReverseSimulateSwap200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDexReverseSimulateSwap200Response)

	if err != nil {
		return err
	}

	*o = DexReverseSimulateSwap200Response(varDexReverseSimulateSwap200Response)

	return err
}

type NullableDexReverseSimulateSwap200Response struct {
	value *DexReverseSimulateSwap200Response
	isSet bool
}

func (v NullableDexReverseSimulateSwap200Response) Get() *DexReverseSimulateSwap200Response {
	return v.value
}

func (v *NullableDexReverseSimulateSwap200Response) Set(val *DexReverseSimulateSwap200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableDexReverseSimulateSwap200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableDexReverseSimulateSwap200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDexReverseSimulateSwap200Response(val *DexReverseSimulateSwap200Response) *NullableDexReverseSimulateSwap200Response {
	return &NullableDexReverseSimulateSwap200Response{value: val, isSet: true}
}

func (v NullableDexReverseSimulateSwap200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDexReverseSimulateSwap200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


