/*
ston-server

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.13.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OperationStat type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OperationStat{}

// OperationStat struct for OperationStat
type OperationStat struct {
	// Address of asset0
	Asset0Address string `json:"asset0_address"`
	// Amount of asset0
	Asset0Amount string `json:"asset0_amount"`
	// Delta of asset0
	Asset0Delta string `json:"asset0_delta"`
	// Reserve of asset0
	Asset0Reserve string `json:"asset0_reserve"`
	// Address of asset1
	Asset1Address string `json:"asset1_address"`
	// Amount of asset1
	Asset1Amount string `json:"asset1_amount"`
	// Delta of asset1
	Asset1Delta string `json:"asset1_delta"`
	// Reserve of asset1
	Asset1Reserve string `json:"asset1_reserve"`
	// Address of destination wallet
	DestinationWalletAddress string `json:"destination_wallet_address"`
	// Operation exit code
	ExitCode string `json:"exit_code"`
	// Liquidity pool fee asset address
	FeeAssetAddress NullableString `json:"fee_asset_address,omitempty"`
	// Liquidity pool fee amount
	LpFeeAmount string `json:"lp_fee_amount"`
	// Liquidity pool token amount change
	LpTokenDelta string `json:"lp_token_delta"`
	// Liquidity pool token amount supply
	LpTokenSupply string `json:"lp_token_supply"`
	// Type of operation
	OperationType string `json:"operation_type"`
	// Address of the pool
	PoolAddress string `json:"pool_address"`
	// Transaction hash
	PoolTxHash string `json:"pool_tx_hash"`
	// Transaction logical time
	PoolTxLt int64 `json:"pool_tx_lt"`
	// Transaction timestamp
	PoolTxTimestamp string `json:"pool_tx_timestamp"`
	// Protocol fee amount
	ProtocolFeeAmount string `json:"protocol_fee_amount"`
	// Referral fee address
	ReferralAddress NullableString `json:"referral_address,omitempty"`
	// Referral fee amount
	ReferralFeeAmount string `json:"referral_fee_amount"`
	// Address of the router
	RouterAddress string `json:"router_address"`
	// Operation is successful
	Success bool `json:"success"`
	// Wallet address
	WalletAddress string `json:"wallet_address"`
	// Transaction hash
	WalletTxHash string `json:"wallet_tx_hash"`
	// Transaction logical time
	WalletTxLt string `json:"wallet_tx_lt"`
	// Transaction timestamp
	WalletTxTimestamp string `json:"wallet_tx_timestamp"`
}

type _OperationStat OperationStat

// NewOperationStat instantiates a new OperationStat object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOperationStat(asset0Address string, asset0Amount string, asset0Delta string, asset0Reserve string, asset1Address string, asset1Amount string, asset1Delta string, asset1Reserve string, destinationWalletAddress string, exitCode string, lpFeeAmount string, lpTokenDelta string, lpTokenSupply string, operationType string, poolAddress string, poolTxHash string, poolTxLt int64, poolTxTimestamp string, protocolFeeAmount string, referralFeeAmount string, routerAddress string, success bool, walletAddress string, walletTxHash string, walletTxLt string, walletTxTimestamp string) *OperationStat {
	this := OperationStat{}
	this.Asset0Address = asset0Address
	this.Asset0Amount = asset0Amount
	this.Asset0Delta = asset0Delta
	this.Asset0Reserve = asset0Reserve
	this.Asset1Address = asset1Address
	this.Asset1Amount = asset1Amount
	this.Asset1Delta = asset1Delta
	this.Asset1Reserve = asset1Reserve
	this.DestinationWalletAddress = destinationWalletAddress
	this.ExitCode = exitCode
	this.LpFeeAmount = lpFeeAmount
	this.LpTokenDelta = lpTokenDelta
	this.LpTokenSupply = lpTokenSupply
	this.OperationType = operationType
	this.PoolAddress = poolAddress
	this.PoolTxHash = poolTxHash
	this.PoolTxLt = poolTxLt
	this.PoolTxTimestamp = poolTxTimestamp
	this.ProtocolFeeAmount = protocolFeeAmount
	this.ReferralFeeAmount = referralFeeAmount
	this.RouterAddress = routerAddress
	this.Success = success
	this.WalletAddress = walletAddress
	this.WalletTxHash = walletTxHash
	this.WalletTxLt = walletTxLt
	this.WalletTxTimestamp = walletTxTimestamp
	return &this
}

// NewOperationStatWithDefaults instantiates a new OperationStat object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOperationStatWithDefaults() *OperationStat {
	this := OperationStat{}
	return &this
}

// GetAsset0Address returns the Asset0Address field value
func (o *OperationStat) GetAsset0Address() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Asset0Address
}

// GetAsset0AddressOk returns a tuple with the Asset0Address field value
// and a boolean to check if the value has been set.
func (o *OperationStat) GetAsset0AddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Asset0Address, true
}

// SetAsset0Address sets field value
func (o *OperationStat) SetAsset0Address(v string) {
	o.Asset0Address = v
}

// GetAsset0Amount returns the Asset0Amount field value
func (o *OperationStat) GetAsset0Amount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Asset0Amount
}

// GetAsset0AmountOk returns a tuple with the Asset0Amount field value
// and a boolean to check if the value has been set.
func (o *OperationStat) GetAsset0AmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Asset0Amount, true
}

// SetAsset0Amount sets field value
func (o *OperationStat) SetAsset0Amount(v string) {
	o.Asset0Amount = v
}

// GetAsset0Delta returns the Asset0Delta field value
func (o *OperationStat) GetAsset0Delta() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Asset0Delta
}

// GetAsset0DeltaOk returns a tuple with the Asset0Delta field value
// and a boolean to check if the value has been set.
func (o *OperationStat) GetAsset0DeltaOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Asset0Delta, true
}

// SetAsset0Delta sets field value
func (o *OperationStat) SetAsset0Delta(v string) {
	o.Asset0Delta = v
}

// GetAsset0Reserve returns the Asset0Reserve field value
func (o *OperationStat) GetAsset0Reserve() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Asset0Reserve
}

// GetAsset0ReserveOk returns a tuple with the Asset0Reserve field value
// and a boolean to check if the value has been set.
func (o *OperationStat) GetAsset0ReserveOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Asset0Reserve, true
}

// SetAsset0Reserve sets field value
func (o *OperationStat) SetAsset0Reserve(v string) {
	o.Asset0Reserve = v
}

// GetAsset1Address returns the Asset1Address field value
func (o *OperationStat) GetAsset1Address() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Asset1Address
}

// GetAsset1AddressOk returns a tuple with the Asset1Address field value
// and a boolean to check if the value has been set.
func (o *OperationStat) GetAsset1AddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Asset1Address, true
}

// SetAsset1Address sets field value
func (o *OperationStat) SetAsset1Address(v string) {
	o.Asset1Address = v
}

// GetAsset1Amount returns the Asset1Amount field value
func (o *OperationStat) GetAsset1Amount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Asset1Amount
}

// GetAsset1AmountOk returns a tuple with the Asset1Amount field value
// and a boolean to check if the value has been set.
func (o *OperationStat) GetAsset1AmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Asset1Amount, true
}

// SetAsset1Amount sets field value
func (o *OperationStat) SetAsset1Amount(v string) {
	o.Asset1Amount = v
}

// GetAsset1Delta returns the Asset1Delta field value
func (o *OperationStat) GetAsset1Delta() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Asset1Delta
}

// GetAsset1DeltaOk returns a tuple with the Asset1Delta field value
// and a boolean to check if the value has been set.
func (o *OperationStat) GetAsset1DeltaOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Asset1Delta, true
}

// SetAsset1Delta sets field value
func (o *OperationStat) SetAsset1Delta(v string) {
	o.Asset1Delta = v
}

// GetAsset1Reserve returns the Asset1Reserve field value
func (o *OperationStat) GetAsset1Reserve() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Asset1Reserve
}

// GetAsset1ReserveOk returns a tuple with the Asset1Reserve field value
// and a boolean to check if the value has been set.
func (o *OperationStat) GetAsset1ReserveOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Asset1Reserve, true
}

// SetAsset1Reserve sets field value
func (o *OperationStat) SetAsset1Reserve(v string) {
	o.Asset1Reserve = v
}

// GetDestinationWalletAddress returns the DestinationWalletAddress field value
func (o *OperationStat) GetDestinationWalletAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DestinationWalletAddress
}

// GetDestinationWalletAddressOk returns a tuple with the DestinationWalletAddress field value
// and a boolean to check if the value has been set.
func (o *OperationStat) GetDestinationWalletAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DestinationWalletAddress, true
}

// SetDestinationWalletAddress sets field value
func (o *OperationStat) SetDestinationWalletAddress(v string) {
	o.DestinationWalletAddress = v
}

// GetExitCode returns the ExitCode field value
func (o *OperationStat) GetExitCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExitCode
}

// GetExitCodeOk returns a tuple with the ExitCode field value
// and a boolean to check if the value has been set.
func (o *OperationStat) GetExitCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExitCode, true
}

// SetExitCode sets field value
func (o *OperationStat) SetExitCode(v string) {
	o.ExitCode = v
}

// GetFeeAssetAddress returns the FeeAssetAddress field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OperationStat) GetFeeAssetAddress() string {
	if o == nil || IsNil(o.FeeAssetAddress.Get()) {
		var ret string
		return ret
	}
	return *o.FeeAssetAddress.Get()
}

// GetFeeAssetAddressOk returns a tuple with the FeeAssetAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OperationStat) GetFeeAssetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FeeAssetAddress.Get(), o.FeeAssetAddress.IsSet()
}

// HasFeeAssetAddress returns a boolean if a field has been set.
func (o *OperationStat) HasFeeAssetAddress() bool {
	if o != nil && o.FeeAssetAddress.IsSet() {
		return true
	}

	return false
}

// SetFeeAssetAddress gets a reference to the given NullableString and assigns it to the FeeAssetAddress field.
func (o *OperationStat) SetFeeAssetAddress(v string) {
	o.FeeAssetAddress.Set(&v)
}
// SetFeeAssetAddressNil sets the value for FeeAssetAddress to be an explicit nil
func (o *OperationStat) SetFeeAssetAddressNil() {
	o.FeeAssetAddress.Set(nil)
}

// UnsetFeeAssetAddress ensures that no value is present for FeeAssetAddress, not even an explicit nil
func (o *OperationStat) UnsetFeeAssetAddress() {
	o.FeeAssetAddress.Unset()
}

// GetLpFeeAmount returns the LpFeeAmount field value
func (o *OperationStat) GetLpFeeAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LpFeeAmount
}

// GetLpFeeAmountOk returns a tuple with the LpFeeAmount field value
// and a boolean to check if the value has been set.
func (o *OperationStat) GetLpFeeAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LpFeeAmount, true
}

// SetLpFeeAmount sets field value
func (o *OperationStat) SetLpFeeAmount(v string) {
	o.LpFeeAmount = v
}

// GetLpTokenDelta returns the LpTokenDelta field value
func (o *OperationStat) GetLpTokenDelta() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LpTokenDelta
}

// GetLpTokenDeltaOk returns a tuple with the LpTokenDelta field value
// and a boolean to check if the value has been set.
func (o *OperationStat) GetLpTokenDeltaOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LpTokenDelta, true
}

// SetLpTokenDelta sets field value
func (o *OperationStat) SetLpTokenDelta(v string) {
	o.LpTokenDelta = v
}

// GetLpTokenSupply returns the LpTokenSupply field value
func (o *OperationStat) GetLpTokenSupply() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LpTokenSupply
}

// GetLpTokenSupplyOk returns a tuple with the LpTokenSupply field value
// and a boolean to check if the value has been set.
func (o *OperationStat) GetLpTokenSupplyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LpTokenSupply, true
}

// SetLpTokenSupply sets field value
func (o *OperationStat) SetLpTokenSupply(v string) {
	o.LpTokenSupply = v
}

// GetOperationType returns the OperationType field value
func (o *OperationStat) GetOperationType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OperationType
}

// GetOperationTypeOk returns a tuple with the OperationType field value
// and a boolean to check if the value has been set.
func (o *OperationStat) GetOperationTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OperationType, true
}

// SetOperationType sets field value
func (o *OperationStat) SetOperationType(v string) {
	o.OperationType = v
}

// GetPoolAddress returns the PoolAddress field value
func (o *OperationStat) GetPoolAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PoolAddress
}

// GetPoolAddressOk returns a tuple with the PoolAddress field value
// and a boolean to check if the value has been set.
func (o *OperationStat) GetPoolAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PoolAddress, true
}

// SetPoolAddress sets field value
func (o *OperationStat) SetPoolAddress(v string) {
	o.PoolAddress = v
}

// GetPoolTxHash returns the PoolTxHash field value
func (o *OperationStat) GetPoolTxHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PoolTxHash
}

// GetPoolTxHashOk returns a tuple with the PoolTxHash field value
// and a boolean to check if the value has been set.
func (o *OperationStat) GetPoolTxHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PoolTxHash, true
}

// SetPoolTxHash sets field value
func (o *OperationStat) SetPoolTxHash(v string) {
	o.PoolTxHash = v
}

// GetPoolTxLt returns the PoolTxLt field value
func (o *OperationStat) GetPoolTxLt() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.PoolTxLt
}

// GetPoolTxLtOk returns a tuple with the PoolTxLt field value
// and a boolean to check if the value has been set.
func (o *OperationStat) GetPoolTxLtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PoolTxLt, true
}

// SetPoolTxLt sets field value
func (o *OperationStat) SetPoolTxLt(v int64) {
	o.PoolTxLt = v
}

// GetPoolTxTimestamp returns the PoolTxTimestamp field value
func (o *OperationStat) GetPoolTxTimestamp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PoolTxTimestamp
}

// GetPoolTxTimestampOk returns a tuple with the PoolTxTimestamp field value
// and a boolean to check if the value has been set.
func (o *OperationStat) GetPoolTxTimestampOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PoolTxTimestamp, true
}

// SetPoolTxTimestamp sets field value
func (o *OperationStat) SetPoolTxTimestamp(v string) {
	o.PoolTxTimestamp = v
}

// GetProtocolFeeAmount returns the ProtocolFeeAmount field value
func (o *OperationStat) GetProtocolFeeAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProtocolFeeAmount
}

// GetProtocolFeeAmountOk returns a tuple with the ProtocolFeeAmount field value
// and a boolean to check if the value has been set.
func (o *OperationStat) GetProtocolFeeAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProtocolFeeAmount, true
}

// SetProtocolFeeAmount sets field value
func (o *OperationStat) SetProtocolFeeAmount(v string) {
	o.ProtocolFeeAmount = v
}

// GetReferralAddress returns the ReferralAddress field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OperationStat) GetReferralAddress() string {
	if o == nil || IsNil(o.ReferralAddress.Get()) {
		var ret string
		return ret
	}
	return *o.ReferralAddress.Get()
}

// GetReferralAddressOk returns a tuple with the ReferralAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OperationStat) GetReferralAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReferralAddress.Get(), o.ReferralAddress.IsSet()
}

// HasReferralAddress returns a boolean if a field has been set.
func (o *OperationStat) HasReferralAddress() bool {
	if o != nil && o.ReferralAddress.IsSet() {
		return true
	}

	return false
}

// SetReferralAddress gets a reference to the given NullableString and assigns it to the ReferralAddress field.
func (o *OperationStat) SetReferralAddress(v string) {
	o.ReferralAddress.Set(&v)
}
// SetReferralAddressNil sets the value for ReferralAddress to be an explicit nil
func (o *OperationStat) SetReferralAddressNil() {
	o.ReferralAddress.Set(nil)
}

// UnsetReferralAddress ensures that no value is present for ReferralAddress, not even an explicit nil
func (o *OperationStat) UnsetReferralAddress() {
	o.ReferralAddress.Unset()
}

// GetReferralFeeAmount returns the ReferralFeeAmount field value
func (o *OperationStat) GetReferralFeeAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ReferralFeeAmount
}

// GetReferralFeeAmountOk returns a tuple with the ReferralFeeAmount field value
// and a boolean to check if the value has been set.
func (o *OperationStat) GetReferralFeeAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReferralFeeAmount, true
}

// SetReferralFeeAmount sets field value
func (o *OperationStat) SetReferralFeeAmount(v string) {
	o.ReferralFeeAmount = v
}

// GetRouterAddress returns the RouterAddress field value
func (o *OperationStat) GetRouterAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RouterAddress
}

// GetRouterAddressOk returns a tuple with the RouterAddress field value
// and a boolean to check if the value has been set.
func (o *OperationStat) GetRouterAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RouterAddress, true
}

// SetRouterAddress sets field value
func (o *OperationStat) SetRouterAddress(v string) {
	o.RouterAddress = v
}

// GetSuccess returns the Success field value
func (o *OperationStat) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *OperationStat) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *OperationStat) SetSuccess(v bool) {
	o.Success = v
}

// GetWalletAddress returns the WalletAddress field value
func (o *OperationStat) GetWalletAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WalletAddress
}

// GetWalletAddressOk returns a tuple with the WalletAddress field value
// and a boolean to check if the value has been set.
func (o *OperationStat) GetWalletAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WalletAddress, true
}

// SetWalletAddress sets field value
func (o *OperationStat) SetWalletAddress(v string) {
	o.WalletAddress = v
}

// GetWalletTxHash returns the WalletTxHash field value
func (o *OperationStat) GetWalletTxHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WalletTxHash
}

// GetWalletTxHashOk returns a tuple with the WalletTxHash field value
// and a boolean to check if the value has been set.
func (o *OperationStat) GetWalletTxHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WalletTxHash, true
}

// SetWalletTxHash sets field value
func (o *OperationStat) SetWalletTxHash(v string) {
	o.WalletTxHash = v
}

// GetWalletTxLt returns the WalletTxLt field value
func (o *OperationStat) GetWalletTxLt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WalletTxLt
}

// GetWalletTxLtOk returns a tuple with the WalletTxLt field value
// and a boolean to check if the value has been set.
func (o *OperationStat) GetWalletTxLtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WalletTxLt, true
}

// SetWalletTxLt sets field value
func (o *OperationStat) SetWalletTxLt(v string) {
	o.WalletTxLt = v
}

// GetWalletTxTimestamp returns the WalletTxTimestamp field value
func (o *OperationStat) GetWalletTxTimestamp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WalletTxTimestamp
}

// GetWalletTxTimestampOk returns a tuple with the WalletTxTimestamp field value
// and a boolean to check if the value has been set.
func (o *OperationStat) GetWalletTxTimestampOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WalletTxTimestamp, true
}

// SetWalletTxTimestamp sets field value
func (o *OperationStat) SetWalletTxTimestamp(v string) {
	o.WalletTxTimestamp = v
}

func (o OperationStat) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OperationStat) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["asset0_address"] = o.Asset0Address
	toSerialize["asset0_amount"] = o.Asset0Amount
	toSerialize["asset0_delta"] = o.Asset0Delta
	toSerialize["asset0_reserve"] = o.Asset0Reserve
	toSerialize["asset1_address"] = o.Asset1Address
	toSerialize["asset1_amount"] = o.Asset1Amount
	toSerialize["asset1_delta"] = o.Asset1Delta
	toSerialize["asset1_reserve"] = o.Asset1Reserve
	toSerialize["destination_wallet_address"] = o.DestinationWalletAddress
	toSerialize["exit_code"] = o.ExitCode
	if o.FeeAssetAddress.IsSet() {
		toSerialize["fee_asset_address"] = o.FeeAssetAddress.Get()
	}
	toSerialize["lp_fee_amount"] = o.LpFeeAmount
	toSerialize["lp_token_delta"] = o.LpTokenDelta
	toSerialize["lp_token_supply"] = o.LpTokenSupply
	toSerialize["operation_type"] = o.OperationType
	toSerialize["pool_address"] = o.PoolAddress
	toSerialize["pool_tx_hash"] = o.PoolTxHash
	toSerialize["pool_tx_lt"] = o.PoolTxLt
	toSerialize["pool_tx_timestamp"] = o.PoolTxTimestamp
	toSerialize["protocol_fee_amount"] = o.ProtocolFeeAmount
	if o.ReferralAddress.IsSet() {
		toSerialize["referral_address"] = o.ReferralAddress.Get()
	}
	toSerialize["referral_fee_amount"] = o.ReferralFeeAmount
	toSerialize["router_address"] = o.RouterAddress
	toSerialize["success"] = o.Success
	toSerialize["wallet_address"] = o.WalletAddress
	toSerialize["wallet_tx_hash"] = o.WalletTxHash
	toSerialize["wallet_tx_lt"] = o.WalletTxLt
	toSerialize["wallet_tx_timestamp"] = o.WalletTxTimestamp
	return toSerialize, nil
}

func (o *OperationStat) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"asset0_address",
		"asset0_amount",
		"asset0_delta",
		"asset0_reserve",
		"asset1_address",
		"asset1_amount",
		"asset1_delta",
		"asset1_reserve",
		"destination_wallet_address",
		"exit_code",
		"lp_fee_amount",
		"lp_token_delta",
		"lp_token_supply",
		"operation_type",
		"pool_address",
		"pool_tx_hash",
		"pool_tx_lt",
		"pool_tx_timestamp",
		"protocol_fee_amount",
		"referral_fee_amount",
		"router_address",
		"success",
		"wallet_address",
		"wallet_tx_hash",
		"wallet_tx_lt",
		"wallet_tx_timestamp",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOperationStat := _OperationStat{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOperationStat)

	if err != nil {
		return err
	}

	*o = OperationStat(varOperationStat)

	return err
}

type NullableOperationStat struct {
	value *OperationStat
	isSet bool
}

func (v NullableOperationStat) Get() *OperationStat {
	return v.value
}

func (v *NullableOperationStat) Set(val *OperationStat) {
	v.value = val
	v.isSet = true
}

func (v NullableOperationStat) IsSet() bool {
	return v.isSet
}

func (v *NullableOperationStat) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOperationStat(val *OperationStat) *NullableOperationStat {
	return &NullableOperationStat{value: val, isSet: true}
}

func (v NullableOperationStat) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOperationStat) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


