/*
ston-server

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.13.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CmcPoolStats type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CmcPoolStats{}

// CmcPoolStats struct for CmcPoolStats
type CmcPoolStats struct {
	// Base token id
	BaseId string `json:"base_id"`
	// Base asset liquidity
	BaseLiquidity string `json:"base_liquidity"`
	// Base token name
	BaseName string `json:"base_name"`
	// Base token symbol
	BaseSymbol string `json:"base_symbol"`
	// Volume of base asset
	BaseVolume string `json:"base_volume"`
	// Last asset quota price in base assets
	LastPrice string `json:"last_price"`
	// Quote token address
	QuoteId string `json:"quote_id"`
	// Quote asset liquidity
	QuoteLiquidity string `json:"quote_liquidity"`
	// Quote token name
	QuoteName string `json:"quote_name"`
	// Quote token symbol
	QuoteSymbol string `json:"quote_symbol"`
	// Volume of quote asset
	QuoteVolume string `json:"quote_volume"`
	// URL to pool
	Url string `json:"url"`
}

type _CmcPoolStats CmcPoolStats

// NewCmcPoolStats instantiates a new CmcPoolStats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCmcPoolStats(baseId string, baseLiquidity string, baseName string, baseSymbol string, baseVolume string, lastPrice string, quoteId string, quoteLiquidity string, quoteName string, quoteSymbol string, quoteVolume string, url string) *CmcPoolStats {
	this := CmcPoolStats{}
	this.BaseId = baseId
	this.BaseLiquidity = baseLiquidity
	this.BaseName = baseName
	this.BaseSymbol = baseSymbol
	this.BaseVolume = baseVolume
	this.LastPrice = lastPrice
	this.QuoteId = quoteId
	this.QuoteLiquidity = quoteLiquidity
	this.QuoteName = quoteName
	this.QuoteSymbol = quoteSymbol
	this.QuoteVolume = quoteVolume
	this.Url = url
	return &this
}

// NewCmcPoolStatsWithDefaults instantiates a new CmcPoolStats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCmcPoolStatsWithDefaults() *CmcPoolStats {
	this := CmcPoolStats{}
	return &this
}

// GetBaseId returns the BaseId field value
func (o *CmcPoolStats) GetBaseId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BaseId
}

// GetBaseIdOk returns a tuple with the BaseId field value
// and a boolean to check if the value has been set.
func (o *CmcPoolStats) GetBaseIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BaseId, true
}

// SetBaseId sets field value
func (o *CmcPoolStats) SetBaseId(v string) {
	o.BaseId = v
}

// GetBaseLiquidity returns the BaseLiquidity field value
func (o *CmcPoolStats) GetBaseLiquidity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BaseLiquidity
}

// GetBaseLiquidityOk returns a tuple with the BaseLiquidity field value
// and a boolean to check if the value has been set.
func (o *CmcPoolStats) GetBaseLiquidityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BaseLiquidity, true
}

// SetBaseLiquidity sets field value
func (o *CmcPoolStats) SetBaseLiquidity(v string) {
	o.BaseLiquidity = v
}

// GetBaseName returns the BaseName field value
func (o *CmcPoolStats) GetBaseName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BaseName
}

// GetBaseNameOk returns a tuple with the BaseName field value
// and a boolean to check if the value has been set.
func (o *CmcPoolStats) GetBaseNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BaseName, true
}

// SetBaseName sets field value
func (o *CmcPoolStats) SetBaseName(v string) {
	o.BaseName = v
}

// GetBaseSymbol returns the BaseSymbol field value
func (o *CmcPoolStats) GetBaseSymbol() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BaseSymbol
}

// GetBaseSymbolOk returns a tuple with the BaseSymbol field value
// and a boolean to check if the value has been set.
func (o *CmcPoolStats) GetBaseSymbolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BaseSymbol, true
}

// SetBaseSymbol sets field value
func (o *CmcPoolStats) SetBaseSymbol(v string) {
	o.BaseSymbol = v
}

// GetBaseVolume returns the BaseVolume field value
func (o *CmcPoolStats) GetBaseVolume() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BaseVolume
}

// GetBaseVolumeOk returns a tuple with the BaseVolume field value
// and a boolean to check if the value has been set.
func (o *CmcPoolStats) GetBaseVolumeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BaseVolume, true
}

// SetBaseVolume sets field value
func (o *CmcPoolStats) SetBaseVolume(v string) {
	o.BaseVolume = v
}

// GetLastPrice returns the LastPrice field value
func (o *CmcPoolStats) GetLastPrice() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastPrice
}

// GetLastPriceOk returns a tuple with the LastPrice field value
// and a boolean to check if the value has been set.
func (o *CmcPoolStats) GetLastPriceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastPrice, true
}

// SetLastPrice sets field value
func (o *CmcPoolStats) SetLastPrice(v string) {
	o.LastPrice = v
}

// GetQuoteId returns the QuoteId field value
func (o *CmcPoolStats) GetQuoteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.QuoteId
}

// GetQuoteIdOk returns a tuple with the QuoteId field value
// and a boolean to check if the value has been set.
func (o *CmcPoolStats) GetQuoteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QuoteId, true
}

// SetQuoteId sets field value
func (o *CmcPoolStats) SetQuoteId(v string) {
	o.QuoteId = v
}

// GetQuoteLiquidity returns the QuoteLiquidity field value
func (o *CmcPoolStats) GetQuoteLiquidity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.QuoteLiquidity
}

// GetQuoteLiquidityOk returns a tuple with the QuoteLiquidity field value
// and a boolean to check if the value has been set.
func (o *CmcPoolStats) GetQuoteLiquidityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QuoteLiquidity, true
}

// SetQuoteLiquidity sets field value
func (o *CmcPoolStats) SetQuoteLiquidity(v string) {
	o.QuoteLiquidity = v
}

// GetQuoteName returns the QuoteName field value
func (o *CmcPoolStats) GetQuoteName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.QuoteName
}

// GetQuoteNameOk returns a tuple with the QuoteName field value
// and a boolean to check if the value has been set.
func (o *CmcPoolStats) GetQuoteNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QuoteName, true
}

// SetQuoteName sets field value
func (o *CmcPoolStats) SetQuoteName(v string) {
	o.QuoteName = v
}

// GetQuoteSymbol returns the QuoteSymbol field value
func (o *CmcPoolStats) GetQuoteSymbol() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.QuoteSymbol
}

// GetQuoteSymbolOk returns a tuple with the QuoteSymbol field value
// and a boolean to check if the value has been set.
func (o *CmcPoolStats) GetQuoteSymbolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QuoteSymbol, true
}

// SetQuoteSymbol sets field value
func (o *CmcPoolStats) SetQuoteSymbol(v string) {
	o.QuoteSymbol = v
}

// GetQuoteVolume returns the QuoteVolume field value
func (o *CmcPoolStats) GetQuoteVolume() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.QuoteVolume
}

// GetQuoteVolumeOk returns a tuple with the QuoteVolume field value
// and a boolean to check if the value has been set.
func (o *CmcPoolStats) GetQuoteVolumeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QuoteVolume, true
}

// SetQuoteVolume sets field value
func (o *CmcPoolStats) SetQuoteVolume(v string) {
	o.QuoteVolume = v
}

// GetUrl returns the Url field value
func (o *CmcPoolStats) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *CmcPoolStats) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *CmcPoolStats) SetUrl(v string) {
	o.Url = v
}

func (o CmcPoolStats) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CmcPoolStats) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["base_id"] = o.BaseId
	toSerialize["base_liquidity"] = o.BaseLiquidity
	toSerialize["base_name"] = o.BaseName
	toSerialize["base_symbol"] = o.BaseSymbol
	toSerialize["base_volume"] = o.BaseVolume
	toSerialize["last_price"] = o.LastPrice
	toSerialize["quote_id"] = o.QuoteId
	toSerialize["quote_liquidity"] = o.QuoteLiquidity
	toSerialize["quote_name"] = o.QuoteName
	toSerialize["quote_symbol"] = o.QuoteSymbol
	toSerialize["quote_volume"] = o.QuoteVolume
	toSerialize["url"] = o.Url
	return toSerialize, nil
}

func (o *CmcPoolStats) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"base_id",
		"base_liquidity",
		"base_name",
		"base_symbol",
		"base_volume",
		"last_price",
		"quote_id",
		"quote_liquidity",
		"quote_name",
		"quote_symbol",
		"quote_volume",
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCmcPoolStats := _CmcPoolStats{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCmcPoolStats)

	if err != nil {
		return err
	}

	*o = CmcPoolStats(varCmcPoolStats)

	return err
}

type NullableCmcPoolStats struct {
	value *CmcPoolStats
	isSet bool
}

func (v NullableCmcPoolStats) Get() *CmcPoolStats {
	return v.value
}

func (v *NullableCmcPoolStats) Set(val *CmcPoolStats) {
	v.value = val
	v.isSet = true
}

func (v NullableCmcPoolStats) IsSet() bool {
	return v.isSet
}

func (v *NullableCmcPoolStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCmcPoolStats(val *CmcPoolStats) *NullableCmcPoolStats {
	return &NullableCmcPoolStats{value: val, isSet: true}
}

func (v NullableCmcPoolStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCmcPoolStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


