/*
ston-server

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.13.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetAssetList200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAssetList200Response{}

// GetAssetList200Response struct for GetAssetList200Response
type GetAssetList200Response struct {
	AssetList []AssetInfoSchema `json:"asset_list"`
}

type _GetAssetList200Response GetAssetList200Response

// NewGetAssetList200Response instantiates a new GetAssetList200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAssetList200Response(assetList []AssetInfoSchema) *GetAssetList200Response {
	this := GetAssetList200Response{}
	this.AssetList = assetList
	return &this
}

// NewGetAssetList200ResponseWithDefaults instantiates a new GetAssetList200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAssetList200ResponseWithDefaults() *GetAssetList200Response {
	this := GetAssetList200Response{}
	return &this
}

// GetAssetList returns the AssetList field value
func (o *GetAssetList200Response) GetAssetList() []AssetInfoSchema {
	if o == nil {
		var ret []AssetInfoSchema
		return ret
	}

	return o.AssetList
}

// GetAssetListOk returns a tuple with the AssetList field value
// and a boolean to check if the value has been set.
func (o *GetAssetList200Response) GetAssetListOk() ([]AssetInfoSchema, bool) {
	if o == nil {
		return nil, false
	}
	return o.AssetList, true
}

// SetAssetList sets field value
func (o *GetAssetList200Response) SetAssetList(v []AssetInfoSchema) {
	o.AssetList = v
}

func (o GetAssetList200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAssetList200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["asset_list"] = o.AssetList
	return toSerialize, nil
}

func (o *GetAssetList200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"asset_list",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetAssetList200Response := _GetAssetList200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetAssetList200Response)

	if err != nil {
		return err
	}

	*o = GetAssetList200Response(varGetAssetList200Response)

	return err
}

type NullableGetAssetList200Response struct {
	value *GetAssetList200Response
	isSet bool
}

func (v NullableGetAssetList200Response) Get() *GetAssetList200Response {
	return v.value
}

func (v *NullableGetAssetList200Response) Set(val *GetAssetList200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAssetList200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAssetList200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAssetList200Response(val *GetAssetList200Response) *NullableGetAssetList200Response {
	return &NullableGetAssetList200Response{value: val, isSet: true}
}

func (v NullableGetAssetList200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAssetList200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


